#!/usr/bin/env node
const { sync } = require('execa')
const c = require('ansi-colors')

console.log(c.green.bold('┏━━━ 📦 Building ━━━━━━━━━━━━━━━━━━━'))
sync('yarn', ['wsrun', '--stages', 'build'], { stdout: 'inherit' })
