#!/usr/bin/env node
const { execSync } = require('child_process')
const c = require('ansi-colors')

console.log(c.blueBright.bold('┏━━━ 🧹 Cleaning ━━━━━━━━━━━━━━━━━━━\n'))
execSync('yarn wsrun -c clean', { stdio: 'inherit' })
