#!/usr/bin/env node
const { sync } = require('execa')
const c = require('ansi-colors')

console.log(c.blueBright.bold('┏━━━ 🧹 Cleaning ━━━━━━━━━━━━━━━━━━━\n'))
sync('yarn', ['wsrun -c clean'], { stdio: 'inherit' })
