#!/usr/bin/env node
const { execSync } = require('child_process');
const c = require('ansi-colors');

console.log(c.cyanBright.bold('┏━━━ 🕵️‍♀️ Lint ━━━━━━━━━━━━━━━━━━━\n'));
execSync('eslint --ext .ts packages/*/src/** --fix', { stdio: 'inherit' });
